# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PyServer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PyServer.proto',
  package='PyServer',
  syntax='proto3',
  serialized_options=_b('\n\010PyServerB\rPyServerProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x0ePyServer.proto\x12\x08PyServer\"\x1f\n\rRewardRequest\x12\x0e\n\x06reward\x18\x01 \x01(\x05\" \n\x0eRewardResponse\x12\x0e\n\x06reward\x18\x01 \x01(\t\" \n\x08Location\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x18\n\x06\x41\x63tion\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x86\x01\n\x08PyServer\x12\x42\n\x0bsendRewards\x12\x17.PyServer.RewardRequest\x1a\x18.PyServer.RewardResponse\"\x00\x12\x36\n\x0csentLocation\x12\x12.PyServer.Location\x1a\x10.PyServer.Action\"\x00\x42!\n\x08PyServerB\rPyServerProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_REWARDREQUEST = _descriptor.Descriptor(
  name='RewardRequest',
  full_name='PyServer.RewardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reward', full_name='PyServer.RewardRequest.reward', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=59,
)


_REWARDRESPONSE = _descriptor.Descriptor(
  name='RewardResponse',
  full_name='PyServer.RewardResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reward', full_name='PyServer.RewardResponse.reward', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=93,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='PyServer.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PyServer.Location.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='PyServer.Location.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=127,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='PyServer.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='PyServer.Action.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['RewardRequest'] = _REWARDREQUEST
DESCRIPTOR.message_types_by_name['RewardResponse'] = _REWARDRESPONSE
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RewardRequest = _reflection.GeneratedProtocolMessageType('RewardRequest', (_message.Message,), {
  'DESCRIPTOR' : _REWARDREQUEST,
  '__module__' : 'PyServer_pb2'
  # @@protoc_insertion_point(class_scope:PyServer.RewardRequest)
  })
_sym_db.RegisterMessage(RewardRequest)

RewardResponse = _reflection.GeneratedProtocolMessageType('RewardResponse', (_message.Message,), {
  'DESCRIPTOR' : _REWARDRESPONSE,
  '__module__' : 'PyServer_pb2'
  # @@protoc_insertion_point(class_scope:PyServer.RewardResponse)
  })
_sym_db.RegisterMessage(RewardResponse)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
  'DESCRIPTOR' : _LOCATION,
  '__module__' : 'PyServer_pb2'
  # @@protoc_insertion_point(class_scope:PyServer.Location)
  })
_sym_db.RegisterMessage(Location)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'PyServer_pb2'
  # @@protoc_insertion_point(class_scope:PyServer.Action)
  })
_sym_db.RegisterMessage(Action)


DESCRIPTOR._options = None

_PYSERVER = _descriptor.ServiceDescriptor(
  name='PyServer',
  full_name='PyServer.PyServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=156,
  serialized_end=290,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendRewards',
    full_name='PyServer.PyServer.sendRewards',
    index=0,
    containing_service=None,
    input_type=_REWARDREQUEST,
    output_type=_REWARDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sentLocation',
    full_name='PyServer.PyServer.sentLocation',
    index=1,
    containing_service=None,
    input_type=_LOCATION,
    output_type=_ACTION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PYSERVER)

DESCRIPTOR.services_by_name['PyServer'] = _PYSERVER

# @@protoc_insertion_point(module_scope)
